import QtQuick

QtObject {
    readonly property var colors: Colors {
    }

    readonly property int space2: 2
    readonly property int space4: 4
    readonly property int space6: 6
    readonly property int space8: 8
    readonly property int space12: 12
    readonly property int space16: 16
    readonly property int space24: 24
    readonly property int radius3: 3
    readonly property int radius8: 8
    readonly property int radius12: 12
    readonly property int radius16: 16
    readonly property int radius24: 24
    readonly property int radiusFull: 999
    readonly property int borderThin: 1
    readonly property int borderMedium: 2
    readonly property int borderSelection: 4
    readonly property int borderEmphasis: 6
    readonly property int fontSizeXs: 10
    readonly property int fontSizeSm: 12
    readonly property int fontSizeMd: 14
    readonly property int fontSizeLg: size16
    readonly property int fontSizeXl: 20
    readonly property int displayIconSize: 56
    readonly property int heroIconSize: 68
    readonly property int size14: 14
    readonly property int size16: 16
    readonly property int size24: 24
    readonly property int size26: 26
    readonly property int size28: 28
    readonly property int size30: 30
    readonly property int size32: 32
    readonly property int size34: 34
    readonly property string textFontFamily: "SF Pro Display"
    readonly property string iconFontFamily: "Symbols Nerd Font"
    readonly property string fontFamily: textFontFamily
    readonly property int fontSize: fontSizeLg
    readonly property int iconFontSize: fontSizeXl
    readonly property int networkRefreshMs: 2000
    readonly property int appLauncherRadius: radius16
    readonly property int appLauncherBorderWidth: borderMedium
    readonly property int appLauncherScreenMargin: 128
    readonly property int appLauncherMaxWidth: 488
    readonly property int appLauncherMaxHeight: 548
    readonly property int appLauncherPadding: space24
    readonly property int appLauncherSectionSpacing: 18
    readonly property int appLauncherSearchHeight: 42
    readonly property int appLauncherSearchRadius: radiusFull
    readonly property int appLauncherSearchBorderWidth: borderMedium
    readonly property int appLauncherSearchHorizontalPadding: space16
    readonly property int appLauncherSearchIconSize: fontSizeLg
    readonly property int appLauncherSearchIconSlotWidth: size24
    readonly property int appLauncherSearchFontSize: fontSizeLg
    readonly property int appLauncherGridCellWidth: 110
    readonly property int appLauncherGridCellHeight: 110
    readonly property int appLauncherEmptyFontSize: fontSizeLg
    readonly property int appLauncherEmptyTextHorizontalMargin: 80
    readonly property int appLauncherCardWidth: 104
    readonly property int appLauncherCardHeight: 104
    readonly property int appLauncherCardRadius: radius12
    readonly property int appLauncherCardPadding: space8
    readonly property int appLauncherCardSpacing: space6
    readonly property int appLauncherCardBorderWidth: borderMedium
    readonly property int appLauncherIconSlotSize: 56
    readonly property int appLauncherIconSize: 52
    readonly property int appLauncherCardLabelFontSize: fontSizeLg
    readonly property int powerMenuActionSpacing: space16
    readonly property int powerMenuActionSize: 136
    readonly property int powerMenuActionRadius: 36
    readonly property int powerMenuActionBorderWidth: borderEmphasis
    readonly property int powerMenuActionIconFontSize: heroIconSize
    readonly property int wallpaperSelectorRadius: radius24
    readonly property int wallpaperSelectorBorderWidth: borderMedium
    readonly property int wallpaperSelectorScreenMargin: 96
    readonly property int wallpaperSelectorMaxWidth: 980
    readonly property int wallpaperSelectorMaxHeight: 680
    readonly property int wallpaperSelectorGridMargin: space24
    readonly property int wallpaperSelectorGridMinCellWidth: 236
    readonly property int wallpaperSelectorGridCellHeight: 170
    readonly property int wallpaperSelectorEmptyFontSize: fontSizeLg
    readonly property int wallpaperSelectorEmptyTextHorizontalMargin: 80
    readonly property int wallpaperCardRadius: radius24
    readonly property int wallpaperCardWidth: 220
    readonly property int wallpaperCardHeight: 150
    readonly property int wallpaperCardBorderWidth: borderSelection
    readonly property int wallpaperCardSelectedBadgeMargin: space12
    readonly property int wallpaperCardSelectedBadgeSize: size32
    readonly property int wallpaperCardSelectedBadgeRadius: radius16
    readonly property int wallpaperCardSelectedBadgeIconFontSize: iconFontSize
    readonly property int screenshotToolRadius: radius24
    readonly property int screenshotToolBorderWidth: borderMedium
    readonly property int screenshotToolScreenMargin: 96
    readonly property int screenshotToolPadding: space24
    readonly property int screenshotToolSectionSpacing: space16
    readonly property int screenshotToolActionWidth: 84
    readonly property int screenshotToolActionHeight: 84
    readonly property int screenshotToolActionRadius: radius12
    readonly property int screenshotToolActionPadding: space8
    readonly property int screenshotToolActionSpacing: space4
    readonly property int screenshotToolActionIconSlotSize: 44
    readonly property int screenshotToolActionIconSize: size28
    readonly property int screenshotToolCursorRowHeight: size24
    readonly property int notificationBadgeSize: space6
    readonly property int notificationBadgeRadius: radius3
    readonly property int notificationBadgeTopMargin: space6
    readonly property int notificationBadgeRightMargin: space8
    readonly property int notificationPopupWidth: 380
    readonly property int notificationPopupTopMargin: 52
    readonly property int notificationPopupRightMargin: space12
    readonly property int notificationPopupBottomMargin: space12
    readonly property int notificationPopupSpacing: space6
    readonly property int notificationPopupEnterAnimationMs: 260
    readonly property int notificationPopupMoveAnimationMs: 220
    readonly property int notificationPopupEnterOffsetMargin: space16
    readonly property int notificationPopupAutoCloseTickMs: 250
    readonly property int notificationCenterPadding: space16
    readonly property int notificationCenterCardWidth: 380
    readonly property real notificationCenterHeightRatio: 0.75
    readonly property int notificationCenterFallbackScreenHeight: 560
    readonly property int notificationCenterRadius: radius16
    readonly property int notificationCenterBorderWidth: borderThin
    readonly property int notificationCenterScreenMargin: space6
    readonly property int notificationCenterTopOffset: 42
    readonly property int notificationCenterSectionSpacing: space12
    readonly property int notificationCenterHeaderHeight: size30
    readonly property int notificationCenterHeaderSpacing: space8
    readonly property int notificationCenterHeaderIconFontSize: fontSizeLg
    readonly property int notificationCenterTextFontSize: fontSizeMd
    readonly property int notificationCenterSpacerHeight: borderThin
    readonly property int notificationCenterClearButtonHeight: size26
    readonly property int notificationCenterClearButtonSpacing: space4
    readonly property int notificationCenterDndRowHeight: size26
    readonly property int notificationCenterDndSwitchWidth: size34
    readonly property int notificationCenterDndSwitchHeight: size16
    readonly property int notificationCenterDndKnobSize: size14
    readonly property int notificationCenterDndKnobMargin: space2
    readonly property int notificationCenterDndAnimationMs: 120
    readonly property int notificationCenterEmptyIconFontSize: displayIconSize
    readonly property int notificationCenterEmptyTextFontSize: fontSizeLg
    readonly property int notificationCenterListSpacing: space12
    readonly property int notificationCenterCardRadius: radius12
    readonly property int notificationCardRadius: radius16
    readonly property int notificationCardSpacing: space8
    readonly property int notificationCardPadding: space8
    readonly property int notificationCardBorderWidth: borderThin
    readonly property int notificationCardIconSlotSize: size32
    readonly property int notificationCardIconSize: size24
    readonly property int notificationCardCloseButtonSize: size24
    readonly property int notificationCardCloseButtonRadius: radiusFull
    readonly property int notificationCardActionButtonHeight: size24
    readonly property int notificationCardActionButtonRadius: radiusFull
    readonly property int notificationCardActionButtonMinWidth: 68
    readonly property int notificationCardActionButtonHorizontalPadding: space16
    readonly property int notificationCardLabelFontSize: fontSizeXs
    readonly property int notificationCardTitleFontSize: fontSizeLg
    readonly property int notificationCardBodyFontSize: fontSizeMd
    readonly property int notificationCardCloseIconFontSize: fontSizeMd
    readonly property int notificationCardCollapsedBodyLines: 2
    readonly property real notificationCardBodyLineHeight: 1.35
    readonly property int notificationCardResizeAnimationMs: 220
    readonly property int notificationCardAllocationFinalizeDelayMs: 32
    readonly property real notificationCardGeometryEpsilon: 0.5
}
