import QtQuick

QtObject {
    readonly property color transparent: "transparent"
    readonly property color mask: "black"
    readonly property color scrim: "#bf1e1e2e"

    readonly property color background: "#1e1e2e"
    readonly property color panel: "#f0181825"
    readonly property color surface: "#181825"
    readonly property color surfaceTransparent: "#0011111b"
    readonly property color surfaceHover: "#45475a"
    readonly property color surfaceActive: "#313244"
    readonly property color surfaceInverse: "#11111b"
    readonly property color border: "#45475a"
    readonly property color borderStrong: "#7f849c"

    readonly property color text: "#cdd6f4"
    readonly property color textMuted: "#bac2de"
    readonly property color textSubtle: "#7f849c"
    readonly property color textInverse: "#11111b"

    readonly property color primary: "#cba6f7"
    readonly property color primaryText: "#11111b"
    readonly property color secondary: "#94e2d5"
    readonly property color focus: "#cba6f7"
    readonly property color selection: "#cba6f7"
    readonly property color selectionText: "#11111b"

    readonly property color info: "#89b4fa"
    readonly property color link: "#89b4fa"
    readonly property color success: "#a6e3a1"
    readonly property color warning: "#f9e2af"
    readonly property color danger: "#f38ba8"
    readonly property color critical: "#f38ba8"

    readonly property color notification: "#f9e2af"
    readonly property color notificationBadge: "#f38ba8"
    readonly property color bluetooth: "#f5c2e7"
    readonly property color network: "#89b4fa"
    readonly property color wifiConnected: "#89b4fa"
    readonly property color wifiDisconnected: "#f38ba8"
    readonly property color backlight: "#f9e2af"
    readonly property color workspaceActive: "#cba6f7"
    readonly property color workspaceUrgent: "#f38ba8"
    readonly property color workspaceRemote: "#89b4fa"
    readonly property color workspaceHover: "#94e2d5"
    readonly property color workspaceOccupied: "#7f849c"
    readonly property color workspaceEmpty: "#45475a"
    readonly property color powerPerformance: "#f38ba8"
    readonly property color powerSaver: "#a6e3a1"
    readonly property color powerBalanced: "#89b4fa"
    readonly property color powerLock: "#fab387"
    readonly property color audioOutput: "#b4befe"
    readonly property color audioInput: "#f2cdcd"
    readonly property color wallpaperSelected: "#f5c2e7"
}
