import QtQuick

QtObject {
    readonly property string workspaceDot: ""
    readonly property string time: "󱑂"
    readonly property string date: "󰨳"
    readonly property string window: "󰰤"
    readonly property string networkThroughput: ""
    readonly property string ethernet: "󰈀"
    readonly property string brightnessControl: "󰌵"
    readonly property string processor: "󰓅"
    readonly property string memory: "󰍛"
    readonly property string wifiConnected: "󰤨"
    readonly property string wifiDisconnected: "󰤭"
    readonly property string bluetoothOff: "󰂲"
    readonly property string bluetoothConnected: "󰂱"
    readonly property string bluetoothOn: "󰂯"
    readonly property string microphoneMuted: ""
    readonly property string microphone: ""
    readonly property string volumeMuted: ""
    readonly property string volumeLow: ""
    readonly property string volumeMedium: ""
    readonly property string volumeHigh: ""
    readonly property string notifications: "󰂚"
    readonly property string notificationsEmpty: "󰂜"
    readonly property string notificationsDnd: "󰂛"
    readonly property string notificationsClear: ""
    readonly property string close: "󰅖"
    readonly property string powerPerformance: "󱠇"
    readonly property string powerSaver: "󱤆"
    readonly property string powerBalanced: "󰚀"
    readonly property var backlightLevels: ["", "", "", "", "", "", "", "", ""]
    readonly property var batteryLevels: ["󰁺", "󰁻", "󰁼", "󰁽", "󰁾", "󰁿", "󰂀", "󰂁", "󰂂"]
    readonly property string batteryFull: "󱃌"
    readonly property string batteryWarning: "󰂃"
    readonly property string batteryCritical: "󱃍"
    readonly property string batteryCharging: "󱘖"
    readonly property string batteryUnknown: "󰂑"
    readonly property string wallpaperSelectedCheck: "✓"
    readonly property string trayBack: "‹"
    readonly property string trayCheck: "✓"
    readonly property string traySubmenu: "›"
}
